### ISSUE TITLE
Progressbar update creates multiple lines

### ISSUE THREAD

**Issue by BookWorm0** [wolph/python-progressbar#291] opened 2023-12-27 02:24 UTC
#### Description
I can reproduce this bug only on Windows, not on macOS. 
I cannot reproduce this bug with package version 4.2.0.

Rename attached bug.py.TXT file to bug.py and run "py bug.py" at a Windows CMD.EXE prompt. 
Result will be as shown in attached screenshot: bug.PNG

Expected behavior is that all progress updates are shown on a single line.

#### Versions

- Python version: 3.12.1
- Python distribution/environment: CPython
- Operating System: Windows 10
- Package version: 4.3.2
![bug](https://github.com/wolph/python-progressbar/assets/46274368/22f27623-af15-47c9-ba3e-983d1ef31d54)
[bug.py.TXT](https://github.com/wolph/python-progressbar/files/13774813/bug.py.TXT)

**Comment by BookWorm0** [comment] 2023-12-28 07:55
This issue looks very similar to #224

**Comment by wolph** [comment] 2024-01-02 11:43
Windows can be a bit tricky in this regard, I've been working on a fix and expect to have it done this week :)

**Comment by BookWorm0** [comment] 2024-01-02 18:19
This bug seems to come back from the grave from time to time.

I understand that the progressbar code needs the file output handle to really be connected to a console, so you can't write a test that plays games with output handle redirection. 

I might be able write a Windows-specific test that could inspect the console output and verify that this bug has not recurred. If I did so, could you make it part of your build verification tests?

**Comment by wolph** [comment] 2024-01-02 18:22
Yes please! It's really hard to detect issues like these and I haven't been able to find a reliable test that actually represents reality in all cases. All help is appreciated!

**Comment by BookWorm0** [comment] 2024-01-03 01:30
This seems to do the trick for me. 
`#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import subprocess

import progressbar
import win32console # "pip install pypiwin32" to get this

_WIDGETS = [progressbar.Percentage(), ' ',
            progressbar.Bar(), ' ',
            progressbar.FileTransferSpeed(), ' ',
            progressbar.ETA()]
_MB = 1024*1024

#---------------------------------------------------------------------------
def scrape_console(line_count):
    pcsb = win32console.GetStdHandle(win32console.STD_OUTPUT_HANDLE)
    csbi = pcsb.GetConsoleScreenBufferInfo()
    col_max = csbi['Size'].X
    row_max = csbi['CursorPosition'].Y

    line_count = min(line_count, row_max)
    lines = []
    for row in range(line_count):
        pct = win32console.PyCOORDType(0, row + row_max - line_count)
        line = pcsb.ReadConsoleOutputCharacter(col_max, pct)
        lines.append(line.rstrip())
    return lines

#---------------------------------------------------------------------------
def runprogress():
    print('***BEGIN***')
    b = progressbar.ProgressBar(widgets = ['example.m4v: '] + _WIDGETS,
                                max_value = 10 * _MB)
    for i in range(10):
        b.update((i+1) * _MB)
        time.sleep(0.25)
    b.finish()
    print('***END***')
    return 0

#---------------------------------------------------------------------------
def find(L, x):
    try:
        return L.index(x)
    except ValueError:
        return -sys.maxsize

#---------------------------------------------------------------------------
def main(argv):
    if argv[1:] == ['--runprogress']:
        return runprogress()

    cp = subprocess.run([sys.executable, __file__, '--runprogress'])
    assert cp.returncode == 0

    scraped_lines = scrape_console(100)
    scraped_lines.reverse() #reverse lines so we find the LAST instances of output.
    index_begin = find(scraped_lines, '***BEGIN***')
    index_end = find(scraped_lines, '***END***')

    if index_end + 2 != index_begin:
        print('ERROR: Unexpected multi-line output from progressbar')
        print(f'{index_begin=} {index_end=}')
        return 1
    return 0

if __name__=='__main__':
    import sys
    exit(main(sys.argv))
`

**Comment by BookWorm0** [comment] 2024-01-03 01:32
Well, that got mangled. I used single backticks, not triple backticks. Trying again...

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import subprocess

import progressbar
import win32console # "pip install pypiwin32" to get this

_WIDGETS = [progressbar.Percentage(), ' ',
            progressbar.Bar(), ' ',
            progressbar.FileTransferSpeed(), ' ',
            progressbar.ETA()]
_MB = 1024*1024

#---------------------------------------------------------------------------
def scrape_console(line_count):
    pcsb = win32console.GetStdHandle(win32console.STD_OUTPUT_HANDLE)
    csbi = pcsb.GetConsoleScreenBufferInfo()
    col_max = csbi['Size'].X
    row_max = csbi['CursorPosition'].Y

    line_count = min(line_count, row_max)
    lines = []
    for row in range(line_count):
        pct = win32console.PyCOORDType(0, row + row_max - line_count)
        line = pcsb.ReadConsoleOutputCharacter(col_max, pct)
        lines.append(line.rstrip())
    return lines

#---------------------------------------------------------------------------
def runprogress():
    print('***BEGIN***')
    b = progressbar.ProgressBar(widgets = ['example.m4v: '] + _WIDGETS,
                                max_value = 10 * _MB)
    for i in range(10):
        b.update((i+1) * _MB)
        time.sleep(0.25)
    b.finish()
    print('***END***')
    return 0

#---------------------------------------------------------------------------
def find(L, x):
    try:
        return L.index(x)
    except ValueError:
        return -sys.maxsize

#---------------------------------------------------------------------------
def main(argv):
    if argv[1:] == ['--runprogress']:
        return runprogress()

    cp = subprocess.run([sys.executable, __file__, '--runprogress'])
    assert cp.returncode == 0

    scraped_lines = scrape_console(100)
    scraped_lines.reverse() #reverse lines so we find the LAST instances of output.
    index_begin = find(scraped_lines, '***BEGIN***')
    index_end = find(scraped_lines, '***END***')

    if index_end + 2 != index_begin:
        print('ERROR: Unexpected multi-line output from progressbar')
        print(f'{index_begin=} {index_end=}')
        return 1
    return 0

if __name__=='__main__':
    import sys
    exit(main(sys.argv))

```

**Comment by BookWorm0** [comment] 2024-01-04 03:22
Test code can be simplified a bit.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time

import progressbar
import win32console # "pip install pypiwin32" to get this

_WIDGETS = [progressbar.Percentage(), ' ',
            progressbar.Bar(), ' ',
            progressbar.FileTransferSpeed(), ' ',
            progressbar.ETA()]
_MB = 1024*1024

#---------------------------------------------------------------------------
def scrape_console(line_count):
    pcsb = win32console.GetStdHandle(win32console.STD_OUTPUT_HANDLE)
    csbi = pcsb.GetConsoleScreenBufferInfo()
    col_max = csbi['Size'].X
    row_max = csbi['CursorPosition'].Y

    line_count = min(line_count, row_max)
    lines = []
    for row in range(line_count):
        pct = win32console.PyCOORDType(0, row + row_max - line_count)
        line = pcsb.ReadConsoleOutputCharacter(col_max, pct)
        lines.append(line.rstrip())
    return lines

#---------------------------------------------------------------------------
def runprogress():
    print('***BEGIN***')
    b = progressbar.ProgressBar(widgets = ['example.m4v: '] + _WIDGETS,
                                max_value = 10 * _MB)
    for i in range(10):
        b.update((i+1) * _MB)
        time.sleep(0.25)
    b.finish()
    print('***END***')
    return 0

#---------------------------------------------------------------------------
def find(L, x):
    try:
        return L.index(x)
    except ValueError:
        return -sys.maxsize

#---------------------------------------------------------------------------
def main(argv):
    runprogress()

    scraped_lines = scrape_console(100)
    scraped_lines.reverse() #reverse lines so we find the LAST instances of output.
    index_begin = find(scraped_lines, '***BEGIN***')
    index_end = find(scraped_lines, '***END***')

    if index_end + 2 != index_begin:
        print('ERROR: Unexpected multi-line output from progressbar')
        print(f'{index_begin=} {index_end=}')
        return 1
    return 0

if __name__=='__main__':
    import sys
    exit(main(sys.argv))

```

**Comment by NairoDorian** [comment] 2024-01-10 08:35
Noticed this issue has well in the last versions

Works as usual in version 4.2.0 though

**Comment by p1r473** [comment] 2024-01-17 21:07
Im having this too and its driving me wild. Im glad its not just me

I can reproduce this with simply the example code on https://pypi.org/project/progressbar2/
```
import time
import progressbar

for i in progressbar.progressbar(range(100)):
    time.sleep(0.02)
```

**Comment by wolph** [comment] 2024-01-24 16:50
@BookWorm0 automated testing remains an issue because the testing code you're using requires an interactive terminal and py.test does not supply one by default. I've been trying alternative methods to get it to work so stay tuned :P

Unfortunately this also means I cannot use `git bisect run` :(

**Comment by BookWorm0** [comment] 2024-01-24 21:12
> @BookWorm0 automated testing remains an issue because the testing code you're using requires an interactive terminal and py.test does not supply one by default. I've been trying alternative methods to get it to work so stay tuned :P
> 
> Unfortunately this also means I cannot use `git bisect run` :(

Sort to hear that. If you don’t have access to a console to scrape, I don’t know how to write the code to automate the test.

**Comment by wolph** [comment] 2024-01-24 21:16
At the very least I've located and fixed the bug so that fix will go out soon :)

If there's no direct py.test solution I can always run a separate test command on windows outside of py.test. Assuming that Github Actions has an active terminal ;)

**Comment by p1r473** [comment] 2024-02-15 22:59
> Im having this too and its driving me wild. Im glad its not just me
> 
> I can reproduce this with simply the example code on https://pypi.org/project/progressbar2/
> 
> ```
> import time
> import progressbar
> 
> for i in progressbar.progressbar(range(100)):
>     time.sleep(0.02)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/9235633/297518427-9196b3d4-9f9d-4f55-97e7-7115fd5e5452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzgxNjEsIm5iZiI6MTcwODAzNzg2MSwicGF0aCI6Ii85MjM1NjMzLzI5NzUxODQyNy05MTk2YjNkNC05ZjlkLTRmNTUtOTdlNy03MTE1ZmQ1ZTU0NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMjI1NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFiNTY3OGYxYzAxNGEzZGY1NGY5MzMzZDY5MzE3NDZjMzFjYjllNzlhMDQ4Y2M4NjU4ZWY0NDg2MmY4ZTNmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TIZVVOI-bnjJrTNIGf5MCl5Gjj0Vk-NTptgYFxaFBls)

Still happening, Im on the latest progressbar2 on Windows

Ive reinstalled latest
```
PS C:\Windows\system32> pip install --upgrade --force-reinstall progressbar2
DEPRECATION: Loading egg at c:\python3\lib\site-packages\vboxapi-1.0-py3.12.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Collecting progressbar2
  Obtaining dependency information for progressbar2 from https://files.pythonhosted.org/packages/7d/66/86ac1b2ad859641bf5186fae72d90ca091a25aee3d6a1ba1772ea19895ba/progressbar2-4.3.2-py3-none-any.whl.metadata
  Using cached progressbar2-4.3.2-py3-none-any.whl.metadata (16 kB)
Collecting python-utils>=3.8.1 (from progressbar2)
  Obtaining dependency information for python-utils>=3.8.1 from https://files.pythonhosted.org/packages/26/45/98431ba6d17b99468bd3f4c53fdeefff402167f006a06773905296f6d489/python_utils-3.8.2-py2.py3-none-any.whl.metadata
  Using cached python_utils-3.8.2-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting typing-extensions>3.10.0.2 (from python-utils>=3.8.1->progressbar2)
  Obtaining dependency information for typing-extensions>3.10.0.2 from https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl.metadata
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Using cached progressbar2-4.3.2-py3-none-any.whl (50 kB)
Using cached python_utils-3.8.2-py2.py3-none-any.whl (27 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Installing collected packages: typing-extensions, python-utils, progressbar2
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.9.0
    Uninstalling typing_extensions-4.9.0:
      Successfully uninstalled typing_extensions-4.9.0
  Attempting uninstall: python-utils
    Found existing installation: python-utils 3.8.2
    Uninstalling python-utils-3.8.2:
      Successfully uninstalled python-utils-3.8.2
  Attempting uninstall: progressbar2
    Found existing installation: progressbar2 4.3.2
    Uninstalling progressbar2-4.3.2:
      Successfully uninstalled progressbar2-4.3.2
Successfully installed progressbar2-4.3.2 python-utils-3.8.2 typing-extensions-4.9.0
```

**Comment by BookWorm0** [comment] 2024-02-16 02:25
> > Im having this too and its driving me wild. Im glad its not just me
> > I can reproduce this with simply the example code on https://pypi.org/project/progressbar2/
> > ```
> > import time
> > import progressbar
> > 
> > for i in progressbar.progressbar(range(100)):
> >     time.sleep(0.02)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/9235633/297518427-9196b3d4-9f9d-4f55-97e7-7115fd5e5452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzgxNjEsIm5iZiI6MTcwODAzNzg2MSwicGF0aCI6Ii85MjM1NjMzLzI5NzUxODQyNy05MTk2YjNkNC05ZjlkLTRmNTUtOTdlNy03MTE1ZmQ1ZTU0NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMjI1NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFiNTY3OGYxYzAxNGEzZGY1NGY5MzMzZDY5MzE3NDZjMzFjYjllNzlhMDQ4Y2M4NjU4ZWY0NDg2MmY4ZTNmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TIZVVOI-bnjJrTNIGf5MCl5Gjj0Vk-NTptgYFxaFBls)
> 
> Still happening, Im on the latest progressbar2 on Windows
> 
> Ive reinstalled latest
> 
> ```
> PS C:\Windows\system32> pip install --upgrade --force-reinstall progressbar2
> DEPRECATION: Loading egg at c:\python3\lib\site-packages\vboxapi-1.0-py3.12.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
> Collecting progressbar2
>   Obtaining dependency information for progressbar2 from https://files.pythonhosted.org/packages/7d/66/86ac1b2ad859641bf5186fae72d90ca091a25aee3d6a1ba1772ea19895ba/progressbar2-4.3.2-py3-none-any.whl.metadata
>   Using cached progressbar2-4.3.2-py3-none-any.whl.metadata (16 kB)
> Collecting python-utils>=3.8.1 (from progressbar2)
>   Obtaining dependency information for python-utils>=3.8.1 from https://files.pythonhosted.org/packages/26/45/98431ba6d17b99468bd3f4c53fdeefff402167f006a06773905296f6d489/python_utils-3.8.2-py2.py3-none-any.whl.metadata
>   Using cached python_utils-3.8.2-py2.py3-none-any.whl.metadata (9.7 kB)
> Collecting typing-extensions>3.10.0.2 (from python-utils>=3.8.1->progressbar2)
>   Obtaining dependency information for typing-extensions>3.10.0.2 from https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl.metadata
>   Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
> Using cached progressbar2-4.3.2-py3-none-any.whl (50 kB)
> Using cached python_utils-3.8.2-py2.py3-none-any.whl (27 kB)
> Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
> Installing collected packages: typing-extensions, python-utils, progressbar2
>   Attempting uninstall: typing-extensions
>     Found existing installation: typing_extensions 4.9.0
>     Uninstalling typing_extensions-4.9.0:
>       Successfully uninstalled typing_extensions-4.9.0
>   Attempting uninstall: python-utils
>     Found existing installation: python-utils 3.8.2
>     Uninstalling python-utils-3.8.2:
>       Successfully uninstalled python-utils-3.8.2
>   Attempting uninstall: progressbar2
>     Found existing installation: progressbar2 4.3.2
>     Uninstalling progressbar2-4.3.2:
>       Successfully uninstalled progressbar2-4.3.2
> Successfully installed progressbar2-4.3.2 python-utils-3.8.2 typing-extensions-4.9.0
> ```

Until there is a fixed version in PyPI, I think the best alternative is to specify a specific older version to pip. (I am using "progressbar2==4.2.0")

**Comment by e-d-n-a** [comment] 2024-02-18 07:05
I can also confirm, that this is still an issue on Windows (every progressbar updates on a newline) with the latest package (v4.3.2).

I ran [the examples](https://progressbar-2.readthedocs.io/en/latest/examples.html) for testing and it's the same behavior with all of them. All updates appear on newlines.
Older v4.2.0 runs the same examples/tests just fine, with them mostly printing on the same line, when updating.

**It can be fixed by explicitly initializing a ProgressBar-instance with the kwarg `line_breaks = False`.**

Then I noticed that the 'line_breaks' attribute of a ProgressBar-instance is `True` (by default), when run as a script,
yet it was `False` (by default), when I tested some code in a Jupyter Console session.
I couldn't yet figure out why that is and how the 'line_breaks' attribute ends up being `True`.
The code is a bit confusing in this regard and I don't know why you set it `True` on the [DefaultFdMixin class in v4.3.2](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L171) (not sure whether this has an effect somewhere).
The code for the [DefaultFdMixin class in v4.2.0](https://github.com/wolph/python-progressbar/blob/0d08718d9ac0e7989c2f8a19caf4cbdab8305212/progressbar/bar.py#L59) looks quite different though.

I might have to investigate this further, but for now I will just use ways to ensure that it's set to `False` by default.

**I suggest, reopening this issue so that people experiencing this bug can notice and track the issue more easily.**

**Comment by e-d-n-a** [comment] 2024-02-18 09:11
### **OK, after further investigation, the issue seems to be this:**

Assuming all arguments are set to their defaults (mostly `None`) and no environment flags are set.
On Windows `sys.stderr.isatty() == True`, yet `progressbar.env.is_ansi_terminal()` will return `False` (for me at least).

The [initialization of the attribute 'line_breaks' in 'class DefaultFdMixin'](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L204C33-L204C55) depends on `self._determine_line_breaks()`.

[In '_determine_line_breaks' ](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L232)(with the 'line_breaks'-argument being `None` by default) the result depends on `self.is_terminal` ('self.line_breaks' will be `True`, if 'self.is_terminal' is `False`).

The [initialization of 'self.is_terminal'](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L203) seems flawed though (it should be set to `True` on a Windows console):

With `is_terminal = None` from the `__init__()` arguments' defaults [`self._determine_is_terminal()`](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L222) depends on the function [`progressbar.env.is_ansi_terminal()`](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/env.py#L90) (which is weird). As it will return `False`, as stated above, so 'self.is_terminal' will become `False` and therefore 'self.line_breaks' becomes `True`.
So why branch here based on 'is_terminal' and use [`progressbar.env.is_terminal()`](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/env.py#L127) only if it is already set!?
What is the reasoning behind this? For me this makes no sense.

`progressbar.env.is_ansi_terminal()` is probably returning `False`on Win7/10/11, although the terminals are somewhat or fully ANSI-compatible.
It seems to rely on environment variables to be set (esp. 'TERM'), which are not used on Windows!?
On the other hand `progressbar.env.is_terminal()` should probably just be used here for non-ANSI-compliant terminals, but isn't with this code structure.

So either `progressbar.env.is_ansi_terminal()` has to be working for Windows terminals or the code should somehow fallback on `progressbar.env.is_ansi_terminal()` as a last resort.

**A solution might be this:**
```
def _determine_is_terminal(
        self,
        fd: base.TextIO,
        is_terminal: bool | None,
    ) -> bool:
        if is_terminal is not None:
            # same result as when going through 'progressbar.env.is_terminal()', but without broken cases
            # 'is_terminal' seems to be meant to always enforce the result anyways
            return bool(is_terminal)
        elif self.is_ansi_terminal:
            # isn't an ansi_terminal also always already a terminal!?
            return True
        else:
            # no need to use 'is_terminal' here, it should override every case anyways
            # otherwise it would break the ansi-case when 'is_terminal == None' and is meant to always override
            return progressbar.env.is_terminal(fd)
```
Should 'self.is_terminal' and 'self.is_ansi_terminal' be set only exclusively, or can they both be True/False?
From the rest of code it seems, that they are independent and can be set freely.
'self.is_terminal' determines 'line_breaks' (True for file logging) and 'self.is_ansi_terminal' may determine 'self.enable_colors'.

**Comment by wolph** [comment] 2024-02-23 12:12
> Then I noticed that the 'line_breaks' attribute of a ProgressBar-instance is `True` (by default), when run as a script, yet it was `False` (by default), when I tested some code in a Jupyter Console session. I couldn't yet figure out why that is and how the 'line_breaks' attribute ends up being `True`. The code is a bit confusing in this regard and I don't know why you set it `True` on the [DefaultFdMixin class in v4.3.2](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L171) (not sure whether this has an effect somewhere).

Line breaks is the safe default since it reduces the output in the case of not using a terminal. In `line_breaks` mode you only get a few updates, in regular mode you get timed updates (potentially many times per second) which could completely overflow your logs (if you redirect your output to a logfile).

Having that said, the `True` is effectively useless and only makes the type checkers happy. It's always set by the `__init__` method if the `__init__` method is called (you could skip it via inheritance).

 I assume, it's supposed to be `False` (by default). The code for the [DefaultFdMixin class in v4.2.0](https://github.com/wolph/python-progressbar/blob/0d08718d9ac0e7989c2f8a19caf4cbdab8305212/progressbar/bar.py#L59) looks quite different though.

They're nearly the same, but there's a small difference due to an oversight on my part:
v4.2.0:
https://github.com/wolph/python-progressbar/blob/0d08718d9ac0e7989c2f8a19caf4cbdab8305212/progressbar/bar.py#L80-L83
v4.3.2:
https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L232-L239
The big bug creating issue here is the `bool()` call. It converts the `None` (undefined) to `False`. I added this in an attempt to reduce bugs by getting everything correctly type checked, but I failed to take into consideration that the `None` as output was important here.

I've already fixed a similar bug elsewhere which fixed it for me on all Windows systems I have access to, but apparently it triggers differently for you.

> **I suggest, reopening this issue so that people experiencing this bug can notice and track the issue more easily.**

The issue isn't meant to close until the release is on PyPI... but github is trying to be smart and immediately closes the issue when a commit with the issue number is pushed.
I wish I could configure it to only close an issue once those commits hit `master` instead of `develop` since it would be a convenient feature.

> With `is_terminal = None` from the `__init__()` arguments' defaults [`self._determine_is_terminal()`](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/bar.py#L222) depends solely on the function [`progressbar.env.is_ansi_terminal()`](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/env.py#L90) (which is weird). As it will return `False`, as stated above, so 'self.is_terminal' will become `False` and therefore 'self.line_breaks' becomes `True`. So why branch here based on 'is_terminal' and use [`progressbar.env.is_terminal()`](https://github.com/wolph/python-progressbar/blob/2207153b0cb0abc0c83279ad2a1079799cd2991e/progressbar/env.py#L127) only if it is already set!? What is the reasoning behind this? For me this makes no sense. 'is_terminal' will enforce the outcome anyways! (probably by design)

It's just the result of one too many refactorings which solved some issues and introduced some others... I'll attempt to clean it up a bit.

> `progressbar.env.is_ansi_terminal()` is probably returning `False`on Win7/10/11, although the terminals are somewhat or fully ANSI-compatible. It seems to mostly rely on environment variables to be set (esp. 'TERM'), which are not used on Windows!? On the other hand `progressbar.env.is_terminal()` should probably just be used here for non-ANSI-compliant or undetermined terminals, but isn't with this code structure.

With the latest version (i.e. what's been on the develop branch the last few weeks) I have proper detection of whether the console supports many colors or not. Oddly enough windows terminals can work in 16 color mode and in ansi mode and in some cases this can be set but not in all cases from what I've seen.

Here's the new code if you're interested: https://github.com/wolph/python-progressbar/blob/5707548cc9dc677c6b66f119bc09bf595eaecb79/progressbar/env.py#L74-L86

> ```
> def _determine_is_terminal(
>         self,
>         fd: base.TextIO,
>         is_terminal: bool | None,
>     ) -> bool:
>         if is_terminal is not None:
>             # same result as when going through 'progressbar.env.is_terminal()', but without broken cases
>             # 'is_terminal' is probably meant to always enforce the result anyways
>             return bool(is_terminal)
>         elif self.is_ansi_terminal:
>             # isn't an ansi_terminal also always already a terminal!?
>             return True
>         else:
>             # no need to use 'is_terminal' here, it should override every case anyways
>             # otherwise it would break the ansi-case when 'is_terminal == None' and is meant to always override
>             return progressbar.env.is_terminal(fd)
> ```

Thank you for the excellent work, I'll test with it to make sure it doesn't break anything else. That's the biggest reason for the messy code... there are exceptions to just about anything in different environments.

> Should 'self.is_terminal' and 'self.is_ansi_terminal' be set only exclusively, or can they both be True/False? From the rest of code it seems, that they are independent and can be set freely. 'self.is_terminal' determines 'line_breaks' (True for file logging) and 'self.is_ansi_terminal' may determine 'self.enable_colors'.

Both can be true. An ansi terminal is always a terminal but not every terminal supports ansi. One of the differences between the two is wether we can freely move the cursor around and write to multiple lines, or if we can only rewrite the current line.

> P.S.: The flawed version of `_determine_is_terminal()` is still used [in dev-branch](https://github.com/wolph/python-progressbar/blob/16c4fcef97882c4fbecefe66516a05e6b80696cf/progressbar/bar.py#L222)!

I'll fix it and test more. Perhaps a few windows VM's will show different results so I can replicate your current issues

Thank you for the amazing detective work!

**Comment by wolph** [comment] 2024-02-24 04:11
I do believe all of the issues on Windows have been fixed. In the mean time I'm also working on improving Jupyter support by using custom widgets but if the current develop version works for everyone than I can already push out a new release with the fixes.

@e-d-n-a Can you test if the current develop branch works for you?

@BookWorm0 I have managed to implement your test so it's less likely to break in the future :)

**Comment by wolph** [comment] 2024-02-25 08:56
I've created a new release with the fixes added. I'm fairly sure this should work in all cases but please let me know if there are still issues so I can reopen the issue.

Additionally Windows now has much better colour support!

**Closed by wolph** 2024-02-25 08:56 UTC

**Comment by p1r473** [comment] 2024-03-04 14:17
Confirmed fixed for me now on Windows. Thanks @wolph also this new color functionality is cool!
