### ISSUE TITLE
version 4.4: interactive shell: arrow keys yield weird symbols

### ISSUE THREAD

**Issue by eachimei** [wolph/python-progressbar#293] opened 2024-02-27 09:10 UTC
#### Description

With version 4.4.1 on Windows, after importing progressbar: pressing any arrow key yield odd symbols on the console:

#### Code
```
>>> import progressbar
>>> ^[[A^[[C^[[D^[[C^[[D^[[C^[[D^[[B^[[D^[[C^[[A^[[C^[[B^[[D   # <-- this is what happens when pressing different arrow keys on the keyboard
```
#### Versions

- Python version: `import sys; print(sys.version)`: 3.10.9
- Python distribution/environment: CPython
- Operating System: Windows 10
- Package version: `import progressbar; print(progressbar.__version__)` : 4.4.1

**Comment by eachimei** [comment] 2024-02-27 09:11
Suspecting this change:

https://github.com/wolph/python-progressbar/commit/a9c677021e963cb419d0eac764ada0ee2f6add79#diff-5bd70fb63160004c558a687f98cb5dfe4a8925be30f161048b96966cd9de054bR170

**Comment by wolph** [comment] 2024-02-27 09:25
You are very likely right... that mode enables 24 bit color support in your terminal but apparently it has side-effects in some cases.

For some reason the console mode isn't reverted back to it's original state once the script is done it seems so that's certainly a bug.

As a quick workaround, I can't reproduce the issue in PowerShell so that might help

**Comment by eachimei** [comment] 2024-02-27 09:28
Thanks for the quick response!
I am able to reproduce it on Powershell as well:
![image](https://github.com/wolph/python-progressbar/assets/88023154/31d6d502-56b5-400a-bd5a-5ed9a95422f8)

**Comment by wolph** [comment] 2024-02-27 09:34
Oh... that's odd. Generally on Linux/Unix systems this is caused by not having `readline` available, but while it's better with readline, it doesn't solve the issue for me it seems.

You can try like this:
```
pip install pyreadline3
```
And after that:
```
import pyreadline3
pyreadline3.Readline()
```

**Comment by eachimei** [comment] 2024-02-27 09:42
Still buggy, this time pressing arrow keys makes parts of the terminal to disappear:
![image](https://github.com/wolph/python-progressbar/assets/88023154/0d50b0e5-6c37-44d8-bcb1-9275762e1e7d)

if I press some more arrow keys, it will erase more chunks:
![image](https://github.com/wolph/python-progressbar/assets/88023154/d6ecef5c-70a7-4ee4-9fb1-7e376af54d54)

**Comment by wolph** [comment] 2024-03-02 15:24
I've pushed a fix to the develop branch, can you see if it works for you?

```
pip install "git+https://github.com/wolph/python-progressbar.git#egg=progressbar2"
```

**Comment by eachimei** [comment] 2024-03-03 07:51
Looks good! The issue does not reproduce with this version (commit 20f1bbb41f751824a28bbe7ea88cedf718b7a12a)

**Closed** 2024-03-04 14:53 UTC

**Comment by wolph** [comment] 2024-03-04 15:29
The new release is online!

**Comment by eachimei** [comment] 2024-03-05 08:25
Thanks @wolph ! I currently don't see a new release (4.4.2 ?) on pypi though:
https://pypi.org/project/progressbar2/#history
![image](https://github.com/wolph/python-progressbar/assets/88023154/6779943a-2940-49af-86f6-2d7dc7b16104)

**Comment by wolph** [comment] 2024-03-05 16:23
Odd... I've attempted to upload it again and it seems to have worked this time :)
![image](https://github.com/wolph/python-progressbar/assets/270571/e5b19822-bd83-4e35-8953-df9814c7599d)

**Comment by eachimei** [comment] 2024-03-05 16:45
Cheers, thank you! Confirmed no issue using 4.4.2 👍
