### ISSUE TITLE
AdaptiveTransferSpeed is not adaptive

### ISSUE THREAD

**Issue by tobiasmaier** [WoLpH/python-progressbar#122] opened 2017-06-02 10:17 UTC
#### Description

AdaptiveTransferSpeed shows the same values as TransferSpeed, it does not calculate the values over the last X samples.

The example code below shows when finished:

> 100% ETA: Time: 0:00:15 Adaptive ETA: Time: 0:00:15 Absolute ETA: Finished at: 0:00:15 Transfer Speed:  33.3 B/s Adaptive Transfer Speed:  33.3 B/s ||

the expected Adaptive Transfer Speed with  `sleep(0.1)` for the last 100 iterations would be `10.0 B/s`

The reason is `FileTransferSpeed` is used to print Adaptive Transfer Speed but calculated and passed parameters _value_ and _total_seconds_elapsed_ are ignored because the keys exist in data.
```
value = data['value'] or value
elapsed = data['total_seconds_elapsed'] or total_seconds_elapsed
```

#### Proposed Fix
Change the code in `FileTransferSpeed.__call__` to
```
value = value or data['value']
elapsed = total_seconds_elapsed or data['total_seconds_elapsed']
```
or to be have the same code as in `ETA.__call__` to:
```
if value is None:
    value = data['value']
if elapsed is None:
    elapsed = data['total_seconds_elapsed']
```

#### Code
Copied from examples and added FileTransferSpeed widget
```
import progressbar
from time import sleep

widgets = [
    progressbar.Percentage(),
    ' ETA: ', progressbar.ETA(),
    ' Adaptive ETA: ', progressbar.AdaptiveETA(),
    ' Absolute ETA: ', progressbar.AbsoluteETA(),
    ' Transfer Speed: ', progressbar.FileTransferSpeed(),
    ' Adaptive Transfer Speed: ', progressbar.AdaptiveTransferSpeed(),
    ' ', progressbar.Bar(),
]
bar = progressbar.ProgressBar(widgets=widgets, max_value=500)
bar.start()
for i in range(500):
    if i < 100:
        sleep(0.02)
    elif i > 400:
        sleep(0.1)
    else:
        sleep(0.01)
    bar.update(i + 1)
bar.finish()
```

#### Versions

- Python version: 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
- Python distribution/environment: CPython
- Operating System: Ubuntu Linux
- Package version: 3.20.0 / git

**Comment by WoLpH** [comment] 2017-06-02 13:33
Thanks for the extensive bug report and the fix! It seems to work great, I'll try to get a new release out within a few days

**Comment by WoLpH** [comment] 2017-06-02 14:09
And the new release is online :)

You can try 3.30.2

**Comment by tobiasmaier** [comment] 2017-06-09 06:47
Something seems to have gone wrong with the pull request (#123) that fixes this issue. The change is not visible in master or develop.

**Comment by martinprikryl** [comment] 2019-09-16 05:39
I also came to report the same bug and the same fix.
I'm happy to see it fixed already.
But unfortunately I still do not see the fix in master nor develop. 
https://github.com/WoLpH/python-progressbar/blob/develop/progressbar/widgets.py#L479
https://github.com/WoLpH/python-progressbar/blob/master/progressbar/widgets.py#L471

**Comment by WoLpH** [comment] 2019-09-17 00:46
This issue has been fixed before but apparently it's broken again somehow. For some reason the previously added tests didn't cover this so I'll add more tests to make sure it won't happen again. 

It seems like #207 is a duplicate of this. I'll get it working again as soon as possible :)

**Comment by WoLpH** [comment] 2019-09-17 13:43
@martinprikryl did you run into the issue of #207 as well or is it broken for you in a different case?

When I run `python examples.py eta_types_demonstration` it appears to be running correctly but I might be missing something :)

**Comment by martinprikryl** [comment] 2019-09-17 13:50
No, I do not get that problem. For me all widgets work. It's just that `AdaptiveTransferSpeed` displays  the same value as `FileTransferSpeed` due to the bug described above by @tobiasmaier.

**Comment by WoLpH** [comment] 2019-09-17 14:00
I could swear I've re-added this code before... either way, it's back again :)

Now the hard part... creating a test for this case ;)

**Closed** 2019-09-17 14:00 UTC

**Comment by WoLpH** [comment] 2019-09-18 00:35
I've finally been able to write a test that consistently works across all testing platforms so I'll create a new release now :)
