### ISSUE TITLE
Support logging module

### ISSUE THREAD

**Issue by d4nst** [WoLpH/python-progressbar#101] opened 2017-03-12 18:35 UTC
#### Description

The `redirect_stdout` option doesn't work when printing messages to stdout using the logging module. 

Is there any workaround for this that I am not aware of? 

#### Code

```
import time
import progressbar

bar = progressbar.ProgressBar(redirect_stdout=True)
for i in bar(range(100)):
    logging.warning('Some warning')
    time.sleep(0.1)
```

**Comment by WoLpH** [comment] 2017-03-12 19:02
Logging generally writes to stderr instead of stdout: https://docs.python.org/2/library/logging.handlers.html#logging.StreamHandler

I assume your problem would be fixed by setting `redirect_stderr=True`

**Comment by d4nst** [comment] 2017-03-12 19:19
That solves the issue. Thanks!

**Comment by WoLpH** [comment] 2017-03-12 21:45
Good to hear :)

**Comment by d4nst** [comment] 2017-03-13 23:20
@WoLpH Unfortunately that only seems to work with the root logger provided by the logging module (like my example above). If I create a new logger and add a `StreamHandler` as shown below, the bar is not displayed correctly.

Any ideas about what could be the issue?

```
import time
import progressbar
import logging

logger = logging.getLogger('my_logger')
logger.addHandler(logging.StreamHandler())

bar = progressbar.ProgressBar(redirect_stdout=True, redirect_stderr=True)
for i in bar(range(100)):
    logger.warning('Some warning')
    time.sleep(0.1)
```

**Comment by WoLpH** [comment] 2017-03-14 00:24
It seems you're quite right. I've done some testing and it's indeed a bit of a problem.
The problem here is that the StreamHandler caches the actual stream: https://hg.python.org/cpython/file/2.7/Lib/logging/__init__.py#l835

The hack that the stderr redirection uses replaces `sys.stderr` with a temporary replacement. The problem is here is that StreamHandler doesn't look at sys.stderr anymore after initialisation. We can hack around it fairly easily but I can't think of a single solution that will work correctly in all cases. [I'v tried overwriting the write method of sys.stderr but sys.stderr doesn't allow overwriting unfortunately](https://github.com/WoLpH/python-progressbar/tree/feature/output-redirection).

You can work around the issue by initializing the progressbar before you initialize the logging handler:
```
import sys
import time
import progressbar
import logging

logger = logging.getLogger('my_logger')

bar = progressbar.ProgressBar(redirect_stdout=True, redirect_stderr=True)
bar.start()

logger.addHandler(logging.StreamHandler())

for i in bar(range(100)):
    logger.warning('Some warning')
    time.sleep(0.1)
```

**Comment by d4nst** [comment] 2017-03-14 00:55
Although that works fine on that specific example, it wouldn't work if I had more than one progressbar. In my application I want to have a global logger for a module and use multiple progressbars in different parts of the code. 

I think the best option in this case is to use the root logger, even though I wouldn't be able to format it the way I want it. Please let me know if you can think of a better workaround.

Thanks!

**Comment by WoLpH** [comment] 2017-03-30 22:50
Warning: this issue has been inactive for 16 days and will be automatically closed on 2017-05-09 if there is no further activity.

**Comment by asetGem** [comment] 2017-04-14 13:24
I'm having the same problem when using my logger with a StreamHandler. Would be really great if you can find a way to solve it.

Thanks!

**Closed** 2017-05-05 01:59 UTC

**Comment by WoLpH** [comment] 2017-05-05 02:01
The new release has a fix for the issue :)

Your options are to employ environment variables:

```sh
WRAP_STDERR=true python your_script.py
```

Or to wrap `stderr` before the `StreamHandler` initiates:

```python
import time
import logging
import progressbar

progressbar.streams.wrap_stderr()
logging.basicConfig()

bar = progressbar.ProgressBar()
for i in bar(range(10)):
    logging.error('Got %d', i)
    time.sleep(0.2)
```

**Comment by pbeza** [comment] 2017-07-28 12:00
I have a problem with your `progressbar.streams.wrap_stderr()` fix – why in the below example neither *Test 1* nor *Test 2* is printed?

```
import time
import logging
import progressbar

progressbar.streams.wrap_stderr()
logging.basicConfig()

bar = progressbar.ProgressBar()
for i in bar(range(10)):
    logging.error('Got %d', i)
    time.sleep(0.2)

logging.error("Test 1")
progressbar.streams.unwrap_stderr()
logging.error("Test 2")
```

**Comment by WoLpH** [comment] 2017-07-28 12:07
That's a bug indeed, see #134 for more info :)
