### ISSUE TITLE
ProgressBar crashes with large max_value

### ISSUE THREAD

**Issue by sndrtj** [WoLpH/python-progressbar#76] opened 2016-06-30 07:57 UTC
On the most recent version from pip (3.9.3), `ProgressBar` crashes when a large `max_value` is supplied. 

The following snippet produces the error:

```python
import progressbar

with progressbar.ProgressBar(max_value=2.4e8) as bar:
    for i in range(int(2.4e8)):
        bar.update(i)
```

The stacktrace is:

```
  0% (   419170 of 240000000) |                                                                                                                                         | Elapsed Time: 0:00:03 ETA:  0:00:00Traceback (most recent call last):
  File "test.py", line 5, in <module>
    bar.update(i)
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 364, in __exit__
    self.finish()
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 526, in finish
    self.update(self.max_value)
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 475, in update
    StdRedirectMixin.update(self, value=value)
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 110, in update
    DefaultFdMixin.update(self, value=value)
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 42, in update
    self.fd.write('\r' + self._format_line())
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 412, in _format_line
    widgets = ''.join(self._format_widgets())
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/bar.py", line 392, in _format_widgets
    widget_output = widget(self, data)
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/widgets.py", line 345, in __call__
    return ETA.__call__(self, progress, data, value=value, elapsed=elapsed)
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/widgets.py", line 282, in __call__
    data['eta'] = utils.format_time(data['eta_seconds'])
  File "/home/sander/.virtualenvs/test2/local/lib/python2.7/site-packages/progressbar/utils.py", line 228, in format_time
    time = datetime.timedelta(seconds=int(time))
OverflowError: normalized days too large to fit in a C int
``` 

This was tested on Ubuntu 14.04, using a fresh virtualenvironment. If I install version 3.6.2, the code in the snippet runs fine.

**Comment by WoLpH** [comment] 2016-06-30 12:28
Perhaps it's an issue with a 32 bit Python install? I can't reproduce it locally but I've created a theoretical fix, can you try that?

**Comment by TimoRoth** [comment] 2016-07-01 11:34
This is also happening for us, with ubuntu 16.04 amd64, python3.5.

**Comment by WoLpH** [comment] 2016-07-01 14:00
Is that also the case for the current development release?

**Comment by dlenski** [comment] 2016-07-03 19:10
Hi @WoLpH and others,

Several users of [tetherback](https://github.com/dlenski/tetherback) have been running into this issue as well: [tetherback #20](https://github.com/dlenski/tetherback/issues/20), [#21](https://github.com/dlenski/tetherback/issues/21).

I can generate it reliably under Ubuntu 15.10 amd64, python 3.5, by running the following script which generates random `max_value` from a log-normal distribution, and then updates the progress bar at random intervals:

```python3
from progressbar import ProgressBar, Percentage, FileTransferSpeed, ETA, DataSize
from time import sleep
from random import lognormvariate, normalvariate
from math import log

for ii in range(100):
    max_value = lognormvariate(log(1000000), log(500000))
    print('{}: max_value={}'.format(ii, max_value))
    
    pbwidgets = ['  test %d: ' % ii, Percentage(), ' ', FileTransferSpeed(), ' ', ETA(), ' ', DataSize() ]
    pbar = ProgressBar(max_value=max_value, widgets=pbwidgets).start()

    cur_value = 0
    while cur_value < max_value:
        pbar.update(cur_value)
        sleep(normalvariate(.2, .05))
        cur_value += max_value/100 * lognormvariate(0, 1)
    pbar.finish()
```

Using v3.9.3 installed via `pip3`:
```sh
$ pip3 list|grep progress
progressbar2 (3.9.3)
```

ps- `progressbar` is awesome. Many, many thanks for this easy-to-use and well-designed library.

**Comment by dlenski** [comment] 2016-07-03 19:45
I just tested using the same test script under progressbar2 v3.6.1 and this problem does not occur.

Even when v3.9.3 *works*, it appears to be displaying the wrong output:

With v3.6.1:

```
$ python3 test_progressbar.py 
0: max_value=20561045808.596012
  test 0: 100%   1.7 GiB/s    Time: 0:00:11     19.1 GiB                                                                                                                       
1: max_value=59023171565202.23
  test 1:  52%   4.6 TiB/s    ETA:  0:00:01     28.4 TiB     
```

With v3.9.3, it's displaying "elapsed time" rather than ETA:

```
$ python3 test_progressbar.py 
0: max_value=229639.24744805894
  test 0:  46%  15.7 KiB/s    Elapsed Time: 0:00:06    104.1 KiB
```

This appears to be because the `Timer.__init__` overwrites the intended `format`
```
    def __init__(
            self,
            format_not_started='ETA:  --:--:--',
            format_finished='Time: %(elapsed)s',
            format='ETA: %(eta)s',
            format_zero='ETA:  0:00:00',
            **kwargs):
        self.format_not_started = format_not_started
        self.format_finished = format_finished
        self.format = format
        self.format_zero = format_zero
        Timer.__init__(self, **kwargs)
```

**Comment by dlenski** [comment] 2016-07-03 19:53
Aha.

It appears that this bug was fixed in cf19031a, which is included in the latest `develop` head, but has not yet been part of a release.

**Comment by WoLpH** [comment] 2016-07-03 23:42
I've uploaded the new release to PyPI. Please let me know if you experience any more errors :)

And if anyone has an idea how I can properly test this... please let me know. All tests on Travis succeeded without any issues which makes it a bit harder for me to test...

**Comment by dlenski** [comment] 2016-07-04 03:05
@WoLpH, I think the reason all the tests pass is that none of them include the combination of the `ETA()` widget with a very large `max_value`.

This is just a dumb kludge, but adding `widgets=[ETA()]` to the new test in `large_values.py` results in a failed test for v3.9.3 but a pass for v3.9.4:

```diff
diff --git a/tests/large_values.py b/tests/large_values.py
index 0786f8c..ee8b231 100644
--- a/tests/large_values.py
+++ b/tests/large_values.py
@@ -3,7 +3,7 @@ import progressbar
 
 
 def test_large_max_value():
-    with progressbar.ProgressBar(max_value=1e10) as bar:
+    with progressbar.ProgressBar(widgets=[progressbar.ETA()], max_value=1e10) as bar:
         for i in range(10):
             bar.update(i)
             time.sleep(0.1)
```

However, **the issue is not fully resolved in v3.9.4**. Trying even larger `max_value` still raises an `OverflowError`:

```diff
diff --git a/tests/large_values.py b/tests/large_values.py
index 0786f8c..e427acb 100644
--- a/tests/large_values.py
+++ b/tests/large_values.py
@@ -3,7 +3,9 @@ import progressbar
 
 
 def test_large_max_value():
-    with progressbar.ProgressBar(max_value=1e10) as bar:
-        for i in range(10):
-            bar.update(i)
-            time.sleep(0.1)
+    for large_max_value in (1e9, 1e10, 1e11, 1e15):
+        with progressbar.ProgressBar(widgets=[progressbar.ETA()],
+                                     max_value=large_max_value) as bar:
+            for i in range(10):
+                bar.update(i)
+                time.sleep(0.1)
```

**Comment by WoLpH** [comment] 2016-07-04 10:30
@dlenski the problem is that none of the examples error on either my system or the automated travis tests. Not even with your new tests.

To illustrate, the results of the tests: https://travis-ci.org/WoLpH/python-progressbar/builds/142172199
Which is running these tests: https://github.com/WoLpH/python-progressbar/blob/b58bb8e4288a5d1717565b3700f0af3784c7e161/tests/large_values.py

**Comment by dlenski** [comment] 2016-07-04 18:27
Sorry, my previous post was inaccurate, because I had not correctly applied 19168aeeb77716103aed01168df139496e8f9796. After applying that, no errors.

So, at least for me, the combination of fixing the bugs in `ETA()` and catching `OverflowError` in `format_time` is doing the trick. :+1:

**Comment by WoLpH** [comment] 2016-07-04 19:23
Ah, perfect

**Closed by WoLpH** 2016-07-04 19:23 UTC
