### ISSUE TITLE
Auto-flushing when wrapping streams?

### ISSUE THREAD

**Issue by davidparsson** [WoLpH/python-progressbar#160] opened 2018-03-26 13:19 UTC
#### Description

Have you considered some kind of auto-flushing when wrapping the streams? In the cases where each progress step takes a while, it would be convenient to get log outputs more frequently without manually calling `progressbar.streams.flush()`. Please run the code below for a frustrating example of too long waiting times.

#### Code

```
import time
import progressbar


with progressbar.ProgressBar(redirect_stdout=True) as progress:
    for i in progress(range(3)):
        for j in range(10):
            time.sleep(0.5)
            print(i, j)
            # progressbar.streams.flush()
```

**Comment by WoLpH** [comment] 2018-03-29 01:00
I've been thinking about this but I can't really think of a good solution within the current system yet.

One possible solution would be to run the progressbar in a separate thread and make it update periodically regardless of what the main thread is doing. That would actually solve many time based issues but it might also introduce threading issues... not entirely sure but I believe it could be a really nice solution for these types of issues.

I'll have to investigate what happens to stdout/stderr during threading though, it might cause more issues than it solves.

**Comment by davidparsson** [comment] 2018-03-29 11:56
Must the flush be initiated by the progress bar? One alternative solution might be that the `WrappedIO` flushes when it is written to. That could possibly be delayed by using a thread (but that's more complex).

**Comment by davidparsson** [comment] 2018-03-29 11:57
That would probably require fixing #159 though.

**Comment by WoLpH** [comment] 2018-03-29 11:58
Good point, that could work as well and would be a lot easier to fix on short notice

**Comment by WoLpH** [comment] 2018-04-02 13:11
I believe I've fixed the issue, can you verify it works for you? :)

**Comment by davidparsson** [comment] 2018-04-02 15:34
This, #161 and #159 are resolved for me as well, but the ETA calculation now seem to be wrong in this example:

```
import time
import progressbar

with progressbar.ProgressBar(max_value=3, redirect_stdout=True) as progress:
    for i in progress(range(3)):
        for j in range(3):
            time.sleep(1)
            print(i, j)
```

I'm not sure if that's a new issue though.

**Comment by WoLpH** [comment] 2018-04-02 18:24
That's a matter of debate I suppose... since there is no new update but some time has passed it's actually accurate but it might not be the expected behaviour...

The alternatives would be to not update the progressbar at all (and print the previous line) or extrapolate the results from the previous result. Extrapolating seems like a completely wrong solution to me since those results could be very wrong (it could easily go beyond 100% for example).

Printing the previous line would be pretty much the same as the old behaviour where the bar was never updated (until the next value).

I personally think the current solution is the most accurate option but I'm open to suggestions :)

**Comment by davidparsson** [comment] 2018-04-03 06:37
I agree that it makes sense to update the estimated ETA, but I think it's a bit pessimistic to estimate it to `23 days, 4:15:30` in the example above, where the first step took 3 seconds.

**Comment by davidparsson** [comment] 2018-04-03 06:39
By the way, if you want to make your unit tests time-aware _and_ fast, I'd like to recommend [freezegun](https://github.com/spulec/freezegun).

**Comment by WoLpH** [comment] 2018-04-03 09:05
That's indeed a bit extreme.

As for freezegun, I looked at it before but I think there is no support for sleep unfortunately: https://github.com/spulec/freezegun/issues/47

**Comment by davidparsson** [comment] 2018-04-03 13:27
Does the progress bar itself call sleep or is that called in the tests only? If it's the latter, there are freezegun methods that would remove the need for sleep and replace those calls entirely.

**Comment by WoLpH** [comment] 2018-04-03 13:30
It's not the progressbar itself but the examples and tests that call `time.sleep`. I've already started on getting it to work, it shouldn't be too hard to hook it within `py.test` and to monkeypatch `time.sleep`

**Comment by WoLpH** [comment] 2018-04-03 15:49
The 23 days was indeed a bug and has been fixed on dev as well. Now I just have to integrate freezegun.

**Closed** 2018-04-04 02:47 UTC

**Comment by WoLpH** [comment] 2018-04-04 02:51
It required a bit of monkey patching but I believe all of the bugs you reported have been fixed now.

Can you check one last time before I create a new release?

**Comment by davidparsson** [comment] 2018-04-06 09:07
Sorry for the delay, but yes, it seems fine now. ⭐️

**Comment by WoLpH** [comment] 2018-04-06 09:08
Fantastic! Thanks for checking, I'll create a new release straight away
